config/routes.rb
Notiz::Application.routes.draw do

  resources :interactions
  resources :sharings

  resources :archives

  resources :trees
  resources :posts
  resources :notes
  resources :clips

  resources :announces

  resources :uploads

  resources :comments
  resources :tests

  resources :notifications

  resources :images
  resources :wallpapers
  resources :attaches
  match ':controller(/:action)/:size/:id.:format' => 'images#show'
  match ':controller(/:action)/:size/:id.:format' => 'wallpapers#show'
  match ':controller(/:action)/:size/:id.:format' => 'clips#show'
  match ':controller(/:action)/:id.format' => 'attach#show'

  resources :tags do
    resources :posts
    resources :notes do
      resources :versions
    end
    resources :clips do
    end
  end

  resources :posts do
    resources :comments
  end

  resources :notes do
    resources :comments
  end

  resources :clips do
    resources :comments
  end

  resources :notes do
    resources :versions
    member do
      get 'status'
    end
  end
  get "notes/status"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :accounts
  resources :users, :controller => :accounts

  get "welcome/index"
  get 'welcome/edm'
  get 'welcome/edm2'

  root :to => 'welcome#index'

end

app/models/note.rb
# encoding: utf-8
class Note < Post
  has_paper_trail :only => [:body], :on => [:update, :destroy]

  def subject
    self[:subject] || "(標題)"
  end

  before_create :init
  def init
    # random_color =  %w(#ccc #000 #fff #e7eb7f #eb8181 #ebbb81 #ebeb81 #abeb81 #81eba3 #81ebd6 #81cfeb #819feb #9181eb #c881eb #eb81eb #eb81bd #eb8181).sort_by{rand()}.first
    color = hsv2rgb
    h = rand(360)
    self.subject_background = hsv2rgb(h, 25, 96) #random_color
    self.body_background = hsv2rgb(h, 25, 96) # random_color
  end

  #h => 0~360 , s => 0~100 , v => 0~100
  def hsv2rgb(h = rand(360),s = 50 + rand(25) ,v = 90 + rand(10))
    # s = 23.0
    # v = 96.0
    h /= 360.0
    s /= 100.0
    v /= 100.0

    i = (h * 6.0).floor;
    f = h * 6.0 - i;
    p = v * (1.0 - s);
    q = v * (1.0 - f * s);
    t = v * (1.0 - (1.0 - f) * s);

    case(i % 6)
    when 0
      i = [v,t,p]
    when 1
      i = [q,v,p]
    when 2
      i = [p,v,t]
    when 3
      i = [p,q,v]
    when 4
      i = [t,p,v]
    when 5
      i = [v,p,q]
    end
    return '#' + i.map{|c|(c*255).to_i.to_s(16).rjust(2,"0")}.join#.to_s
  end

  def subject_background
    nnote ? nil : (options && options[:subject_background] ? options[:subject_background] : '#f0f4b7')
  end

  def body_background
    nnote ? nil : (options && options[:body_background] ? options[:body_background] : '#f0f4b7')
  end
  #  def rand_color(h=rand,s=rand*0.25+0.5,v=rand/10.0+0.9)
  #    @rand_seed = (@rand_seed||rand(6))+1
  #    p = v*(1-s);
  #    q = v*(1-h*s);
  #    t = v*(1-(1-h)*s);
  #    '#' + case(@rand_seed % 6)
  #    when 0;[v,t,p];when 1;[q,v,p]
  #    when 2;[p,v,t];when 3;[p,q,v]
  #    when 4;[t,p,v];when 5;[v,p,q]
  #    #end.map{|c|(c*255).to_i.to_s(16).rjust(2,"0")}.to_s
  #    end.map{|c|(c*255).to_i.to_s(16).rjust(2,"0")}.join
  #  end


  #  def self.migrate_to_options!
  #    self.each do |note|
  #      custome_options.each do |k, v|
  #        unless options && options[k]
  #          if options = {k
  #        end
  #    end
  #  end

  #  has_dynamic_attributes
  #  $dynamic_attrs = [
  #    ['width', 'integer', 300],
  #    ['height', 'integer', 200],
  #    ['x', 'integer', 0],
  #    ['y', 'integer', 0]
  #  ]
  # acts_as_dynamic_attributes($dynamic_attrs)
end

app/controllers/notes_controller.rb
# encoding: utf-8
class NotesController < PostsController
  respond_to :js, :html
  layout "notes"
  before_filter :tag

  def index
    @notes = @tag.posts_order_by_float(:page => params[:page])
    debug @tag.notes_list

    gon.num_pages = @notes.num_pages

    debug gon.num_pages

    respond_to do |format|
      format.js {
        if params[:page]
          if @notes.present?
            render :action => "page", :content_type => :html, :layout => false
          else
            render :text => nil, :status => 404
          end
        else
          render :content_type => :html, :layout => false
        end
      }
      format.html{ }
      #format.mobile{ render :layout => false}
    end
  end

  def show
    @note = Note.find(params[:id])
    # render @note, :layout => false
    respond_to do |format|
      format.html{ render  :layout => 'notes_show'}
    end
  end

  def create
    @tag = params[:tag_id] ? Tag.find(params[:tag_id]) : Tag.order('id').first
    flash[:notice] = "新增便條紙。" if @note = @tag.notes.create!(params[:note])

    respond_to do |format|
      format.js{ render @note, :content_type => :html, :layout => false}
      # format.js { render :json => @note, :content_type => 'text/json' }
    end
  end

  def edit
    @note = Note.find(params[:id])
    respond_to do |format|
      format.js {}
      format.html {}
    end
    # render :layout => false
  end

  #  def status
  #    @note = Note.find(params[:note][:id])
  #    @msg = {:note => @note.id, "locking" => params[:note][:locking]}
  #    respond_with do |format|
  #      format.js{ }
  #    end
  #  end

  def update
    @note = Note.find(params[:id])
    @note.update_attributes(params[:note])
    @keys = params[:note].keys
    debug @token
    flash[:notice] = '便條紙更新完成。'
    respond_with @note do |format|
      format.js { }
      format.html {
        redirect_to tag_notes_path(@note.tag), :notice => flash[:notice]
      }
    end
    rescue Exception => exception
      flash[:notice] = exception.message
      render :nothing => true, :status => 500
  end

  private
  def tag
    return unless params[:tag_id]
    @tag = Tag.find(params[:tag_id])
  end
end

app/views/notes/_content.html.haml
.toolbar
  = link_to '#', post_comments_path(note), :class => 'open_comments icon icons_comments', :title => '留言板'
  = link_to '#', edit_tag_note_path(@tag, note), :class => 'edit icon icons_edit', :title => '全編輯器'
  = link_to "#", note_path(note), :class => 'icon icons_preview', :target => '_blank', :title => '預覽'
  = link_to '#', '#', :class => 'subject_background icon icons_bgcolor', :title => '設定標題底色' if @tag.float && !note.nnote
  = link_to '#', '#', :class => 'background_picker body_background  icon icons_bgcolor', :title => '設定貼紙底色' if !note.nnote
  = link_to '#', '#', :class => 'undo icon icons_undo', :title => '備存版本'
  = link_to '#', '#', :class => 'config icon icons_config', :title => '設定'
.option
  .content
  .footer
    = link_to '', '#', :class => 'close_30 icon icons_close'
.subject{:style => "background: #{note.subject_background}"}
  = raw note.subject
.body{:style => "background: #{note.body_background}"}
  = raw auto_link(note.body, :sanitize => false)
.comments

app/views/notes/_form.html.haml
.hidden
  = form_for @note do |f|
    = f.text_area :body, :id => 'body'# dom_id(@note, 'editor'), :class => 'editor'

= javascript_include_tag "/ckeditor/ckeditor"
:coffeescript
  $(document).ready ->
    CKEDITOR.replace('body', {width: '100%', height: 200});

  CKEDITOR.on "instanceReady", (evt) ->
    editor = evt.editor
    editor.execCommand "maximize"

app/views/notes/_note.html.haml
- if @tag.float
  .note{:id => dom_id(note), :class => "post #{note.classes}", :style => "width: #{note.width}px; height: #{note.height}px;"}
    = render :partial => '/notes/content', :locals => {:note => note}

- else
  .note{:id => dom_id(note), :class => "post #{note.classes}", :style => "position:absolute; left:#{note.left}px; top:#{note.top}px; width:#{note.width}px; height:#{note.height}px"}
    = render :partial => '/notes/content', :locals => {:note => note}

:coffeescript
  $(document).ready ->
    $.fn.initial_note "##{dom_id(note)}"

app/views/notes/_note.mobile.haml
.note.list
  .subject
    = raw link_to(strip_tags(note.subject), tag_note_path(@tag.id, note.id))
    .footer= about(note)

app/views/notes/_toolbar.html.haml
- if params[:tag_id]
  #notes_toolbar
    = link_to '+', '#', :class => 'icon icons_add_note', :id => 'add_note', :title => '新增便條紙'
    %span.memo.dirty
      = link_to '#', 'javascript:void(0)', :class => 'dirty_icon', :title => "書寫時，可隨時按 F2 或 Ctrl-S 存檔"
      (F2)

app/views/notes/edit.html.haml
= render 'form'

app/views/notes/edit.mobile.haml
.hidden
  = form_for @note do |f|
    = f.text_area :body, :id => 'body'

= javascript_include_tag "/ckeditor/ckeditor"
:coffeescript
  $(document).ready ->
    CKEDITOR.replace('body', {width: '100%', height: 200});

  CKEDITOR.on "instanceReady", (evt) ->
    editor = evt.editor
    editor.execCommand "maximize"

app/views/notes/index.html (beauty's conflicted copy 2012-10-16).haml
#notes.clearfix.notes{:class => @tag.mode}
  #tag_tools
    = link_to '#', '#', :class => 'config icon icons_config'
    = render :partial => 'notes/toolbar'
  #infos
    %span.info
      %span#num
        = @notes.all.count
      張便條紙
    %span.info
      共用: #{@tag.sharings.present? ? @tag.sharings.map{|s| content_tag(:span, s.email.split('@')[0], :title => s.email, :id => s.token, :class => 'sharing', "data-token" => s.token).html_safe}.join('').html_safe : '(無)'}, 擁有者: #{@tag.user == current_user ? "你" : @tag.user.email.split('@')[0]}
  = render @notes


-#pictures.es-carousel-wrapper
  .es-carousel
    %ul
      = @tag.pictures.each do |picture|
        %li= link_to image_tag(picture_path(picture, :size => 'small')), '#'


#attaches
  = render @tag.attaches

#upload_images
  .upload_images.icon.icons_photo{:title => '檔案上傳: 直接從檔案總管中拖取檔案放入此處。可同時多檔上傳。支援各種副檔名。圖檔以圖卡方式呈現。'}
  .memo
    檔案上傳
#upload_wallpapers
  .upload_wallpapers.icon.icons_wallpaper{:title => '更換桌布: 直接從檔案總管中拖取圖檔放入此處。多檔時以最後一檔為設定。目前支援 jpeg, jpg, png, gif 四種副檔名。'}
  .memo
    更換桌面

:coffeescript
  $(document).ready ->
    $ ->
      faye = new Faye.Client("#{APP[:url]}:9292/api")
      faye.subscribe "/announces", (data) ->
        data = JSON.parse(unescapeHTML(data))
        subject = data.announce.subject
        if subject == 'close!'
          $('#announce').fadeOut(1000)
        else
          $.fn.log subject, 'subject'
          $('#announce').detach()
          $data = $("<div id='announce'>系統通知: <br/>" + subject + "</div>")
          $.fn.log $data, '#data'
          $data.hide().prependTo($('body')).fadeIn(1000)
          $.fn.log 'msg from announces channel'


    $ ->
      faye = new Faye.Client("#{APP[:url]}:9292/api")
      faye.subscribe "/#{@tag.token}/notes", (data) ->
        data = JSON.parse(unescapeHTML(data))
        $.fn.log data

        # 留言同步
        $.fn.log $("#comment_" + data.id).length
        if data.comment
          obj = data
          $target = $('#' + obj.dom_id)
          $content = $target.find('.comments .content')
          $.fn.log $content
          $.fn.log $(obj.content)
          $(obj.content).appendTo($content)
          $content.scrollTo 'max'

        # 便條紙同步
        if data.note && (parseInt(data.note.options['timestamping']) != Notiz.posts.current.timestamping)
          $.fn.log 'reload!'
          obj = data.note
          $.fn.log obj
          $this = $("#note_" + obj.id)
          if $this.hasClass('nnote')
            $this.find('.subject').css 'background', obj.options.subject_background
            $this.find('.body').css 'background', obj.options.body_background
            $.fn.setColor($this)
          $this.find('.subject').html obj.subject
          $this.find('.body').html obj.body
          $this.width obj.options.width
          $this.height obj.options.height
          $.fn.note_resize_body($this, '.body')
          if !Notiz.tags.current.float()
            $this.css 'left', obj.options.left
            $this.css 'top', obj.options.top
        # 圖卡同步
        if data.clip
          obj = data.clip
          $this = $("#clip_" + obj.id)
          $this.find('.colorbox').html obj.body
          $this.width obj.options.width
          $this.height obj.options.height
          if !Notiz.tags.current.float()
            $this.css 'left', obj.options.left
            $this.css 'top', obj.options.top
          $this.find('img').width obj.options.width
          $this.find('img').height obj.options.height
        $.fn.ajax_reset()


    $('.attach .toolbar .del').unbind('click').click (e) ->
      $attach = $(e.target).closest('.attach')
      if confirm('刪除附件: ' + $attach.find('.download').attr('title') + '?')
        $.fn.log 'del!' + $attach.id()
        $.ajax
          url: '/attaches/' + $attach.id()
          type: 'delete'
          success: ->
            $.fn.log 'delete ok!'
            $attach.fadeOut(300)
      else
        $.fn.log 'not del!'

    $('.sharing').unbind('click').click (e) ->
      if confirm("確定關閉這個分享？")
        $.fn.log $(this).data 'token'
        $.ajax
          url: '/sharings/' + $(this).data('token')
          type: 'delete'
          success: ->
            $(e.target).fadeOut(500)

app/views/notes/index.html.haml
#notes.clearfix.notes{:class => @tag.mode}
  #tag_tools
    = link_to '#', '#', :class => 'config icon icons_config'
    = render :partial => 'notes/toolbar'
  #infos
    %span.info
      %span#num
        = @notes.all.count
      張便條紙
    %span.info
      共用: #{@tag.sharings.present? ? @tag.sharings.map{|s| content_tag(:span, s.email.split('@')[0], :title => s.email, :id => s.token, :class => 'sharing', "data-token" => s.token).html_safe}.join('').html_safe : '(無)'}, 擁有者: #{@tag.user == current_user ? "你" : @tag.user.email.split('@')[0]}
  = render @notes


-#pictures.es-carousel-wrapper
  .es-carousel
    %ul
      = @tag.pictures.each do |picture|
        %li= link_to image_tag(picture_path(picture, :size => 'small')), '#'


#attaches
  = render @tag.attaches

#upload_images
  .upload_images.icon.icons_photo{:title => '檔案上傳: 直接從檔案總管中拖取檔案放入此處。可同時多檔上傳。支援各種副檔名。圖檔以圖卡方式呈現。'}
  .memo
    檔案上傳
#upload_wallpapers
  .upload_wallpapers.icon.icons_wallpaper{:title => '更換桌布: 直接從檔案總管中拖取圖檔放入此處。多檔時以最後一檔為設定。目前支援 jpeg, jpg, png, gif 四種副檔名。'}
  .memo
    更換桌面

:coffeescript
  $(document).ready ->
    $('#tag_tools .config').click (e) ->
      $.ajax
        url: '/tags/' + Notiz.tags.current.id + '/edit'
        success: (data, textStatus, jqXHR) ->
          $("#tag_config_form").detach()
          $(data).hide().insertAfter($(e.target)).slideDown
            duration: 1000
            easing: 'easeOutBounce'
      false

    $ ->
      faye = new Faye.Client("#{APP[:url]}:9292/api")
      faye.subscribe "/announces", (data) ->
        data = JSON.parse(unescapeHTML(data))
        subject = data.announce.subject
        if subject == 'close!'
          $('#announce').fadeOut(1000)
        else
          $.fn.log subject, 'subject'
          $('#announce').detach()
          $data = $("<div id='announce'>系統通知: <br/>" + subject + "</div>")
          $.fn.log $data, '#data'
          $data.hide().prependTo($('body')).fadeIn(1000)
          $.fn.log 'msg from announces channel'


    $ ->
      faye = new Faye.Client("#{APP[:url]}:9292/api")
      faye.subscribe "/#{@tag.token}/notes", (data) ->
        data = JSON.parse(unescapeHTML(data))
        $.fn.log data

        # 留言同步
        $.fn.log $("#comment_" + data.id).length
        if data.comment
          obj = data
          $target = $('#' + obj.dom_id)
          $content = $target.find('.comments .content')
          $.fn.log $content
          $.fn.log $(obj.content)
          $(obj.content).appendTo($content)
          $content.scrollTo 'max'

        # 便條紙同步
        if data.note && (parseInt(data.note.options['timestamping']) != Notiz.posts.current.timestamping)
          $.fn.log 'reload!'
          obj = data.note
          $.fn.log obj
          $this = $("#note_" + obj.id)
          if $this.hasClass('nnote')
            $this.find('.subject').css 'background', obj.options.subject_background
            $this.find('.body').css 'background', obj.options.body_background
            $.fn.setColor($this)
          $this.find('.subject').html obj.subject
          $this.find('.body').html obj.body
          $this.width obj.options.width
          $this.height obj.options.height
          $.fn.note_resize_body($this, '.body')
          if !Notiz.tags.current.float()
            $this.css 'left', obj.options.left
            $this.css 'top', obj.options.top
        # 圖卡同步
        if data.clip
          obj = data.clip
          $this = $("#clip_" + obj.id)
          $this.find('.colorbox').html obj.body
          $this.width obj.options.width
          $this.height obj.options.height
          if !Notiz.tags.current.float()
            $this.css 'left', obj.options.left
            $this.css 'top', obj.options.top
          $this.find('img').width obj.options.width
          $this.find('img').height obj.options.height
        $.fn.ajax_reset()


    $('.attach .toolbar .del').unbind('click').click (e) ->
      $attach = $(e.target).closest('.attach')
      if confirm('刪除附件: ' + $attach.find('.download').attr('title') + '?')
        $.fn.log 'del!' + $attach.id()
        $.ajax
          url: '/attaches/' + $attach.id()
          type: 'delete'
          success: ->
            $.fn.log 'delete ok!'
            $attach.fadeOut(300)
      else
        $.fn.log 'not del!'

    $('.sharing').unbind('click').click (e) ->
      if confirm("確定關閉這個分享？")
        $.fn.log $(this).data 'token'
        $.ajax
          url: '/sharings/' + $(this).data('token')
          type: 'delete'
          success: ->
            $(e.target).fadeOut(500)

app/views/notes/index.mobile.haml
.nav
  .tag= @tag.name
= render @notes

app/views/notes/page.html.haml
= render @notes

app/views/notes/show.html.haml
%h1.subject
  = raw auto_link(@note.subject, :sanitize => false)
.body
  = raw auto_link(@note.body, :sanitize => false)

app/views/notes/show.mobile.haml
.nav
  .tag= link_to @note.tag.name, tag_path(@note.tag)
  >
  = strip_tags @note.subject
  = link_to '(Edit)', edit_tag_note_path(@note.tag, @note)
.note
  .body
    = raw auto_link(@note.body, :sanitize => false)