config/routes.rb
Notiz::Application.routes.draw do

  resources :interactions
  resources :sharings

  resources :archives

  resources :trees
  resources :posts
  resources :notes
  resources :clips

  resources :announces

  resources :uploads

  resources :comments
  resources :tests

  resources :notifications

  resources :images
  resources :wallpapers
  resources :attaches
  match ':controller(/:action)/:size/:id.:format' => 'images#show'
  match ':controller(/:action)/:size/:id.:format' => 'wallpapers#show'
  match ':controller(/:action)/:size/:id.:format' => 'clips#show'
  match ':controller(/:action)/:id.format' => 'attach#show'

  resources :tags do
    resources :posts
    resources :notes do
      resources :versions
    end
    resources :clips do
    end
  end

  resources :posts do
    resources :comments
  end

  resources :notes do
    resources :comments
  end

  resources :clips do
    resources :comments
  end

  resources :notes do
    resources :versions
    member do
      get 'status'
    end
  end
  get "notes/status"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :accounts
  resources :users, :controller => :accounts

  get "welcome/index"
  get 'welcome/edm'
  get 'welcome/edm2'

  root :to => 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def edm
    render :layout => false
  end

  def edm2
    render :layout => false
  end
end

app/views/welcome/edm.html (beauty's conflicted copy 2012-10-16).haml
%style
  @import url(http://fonts.googleapis.com/css?family=Andika|Julee|Pinyon+Script|Meddon|Convergence);
  #w, #c, table{border:1px solid #ccc}
  #w, #c, table{border:none}

%div{:style => 'width: 820px; margin: 0 auto'}
  %hr{:style => 'margin: 30px 0; background: #ccc; color: #ccc'}
  %table{:style => 'width: 70px; margin: 0 auto;'}
    %tr
      %td{:style => 'font-size:30px; line-height:1; font-family:Andika; padding-left:20px'}
        A chirpy birthday
      %td{:style => 'vertical-align:bottom; font-size:12px; padding-left:280px; line-height:1; text-align:right; color: #ccc'}
        = link_to "看更多生日卡", '#'
        = link_to "與好友分享喜悅", '#', :style => 'margin-left: 10px; background:url(http://cactis.airfont.com/assets/images/filenames/1774/original/ico-facebook-small.gif) no-repeat; padding-left: 16px'

  %div{:style => 'width: 820px; margin: 0 auto; padding: 10px;'}
    %table{:style => 'margin: 10px 0 0 10px; width: 738px; height: 360px', :background => 'http://cactis.airfont.com/assets/images/filenames/1773/original/bg-slide-box.gif'}
      %tr
        %td{:style => 'padding: 0; verticel-align:center; text-align:center; width: 474px; height: 316px; text-align: center; vertical-align: center'}
          = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1772/original/img-22.jpg"), '#'
        %td{:style => 'padding: 10px 0 0 10px; font-size: 13.5px;'}
          %div
            %span{:style => "font-size:50px; font-family: 'Pinyon Script', Julee"}
              Dear
            %span
              楊先生,
          %div{:style => 'padding:20px 10px 20px 80px; line-height:1.6'}
            在這個特別的日子
            %br
            我願以這張生日卡
            %br
            獻上最真誠的祝福
            %br
            也期望您的每一天
            %br
            都能平安 順心 美滿
            %br
            真心祝福您
            %br
            生日快樂!
          %div{:style => "text-align:right; margin-left:80px; font-family:Convergence"}
            大紀元時報 業務 Sam 敬上

  %hr{:style => 'margin: 30px 0; background: #ccc; color: #ccc'}
  %table{:style => 'font-weight: bold; font-family: Andika; vertical-align: center; color: #1967B1; width: 820px; margin: 0 auto; font-size: 14px; padding-right: 10px; padding: 15px'}
    %tr
      %td{:style => 'width: 240px; vertical-align: center; text-align: right'}
        此張卡片寄送服務 by
      %td{:style => 'width: 140px;'}
        = link_to image_tag('http://cactis.airfont.com/assets/images/filenames/1776/original/sub-logo.gif'), '#'
      %td{:style => 'vertical-align: bottom'}
        = link_to image_tag('http://cactis.airfont.com/assets/images/filenames/1777/original/btn-blue.gif'), '#'
  %div{:style => 'text-align: center'}
    %img{:src => 'http://cactis.airfont.com/assets/images/filenames/1778/original/img-ad-03.jpg'}

app/views/welcome/edm.html.haml
%style
  @import url(http://fonts.googleapis.com/css?family=Andika|Julee|Pinyon+Script|Meddon|Convergence);
  #w, #c, table{border:1px solid #ccc}
  #w, #c, table{border:none}

%div{:style => 'width: 820px; margin: 0 auto'}
  %hr{:style => 'margin: 30px 0; background: #ccc; color: #ccc'}
  %table{:style => 'width: 70px; margin: 0 auto;'}
    %tr
      %td{:style => 'font-size:30px; line-height:1; font-family:Andika; padding-left:20px'}
        A chirpy birthday
      %td{:style => 'vertical-align:bottom; font-size:12px; padding-left:280px; line-height:1; text-align:right; color: #ccc'}
        = link_to "看更多生日卡", '#'
        = link_to "與好友分享喜悅", '#', :style => 'margin-left: 10px; background:url(http://cactis.airfont.com/assets/images/filenames/1774/original/ico-facebook-small.gif) no-repeat; padding-left: 16px'

  %div{:style => 'width: 820px; margin: 0 auto; padding: 10px;'}
    %table{:style => 'margin: 10px 0 0 10px; width: 738px; height: 360px', :background => 'http://cactis.airfont.com/assets/images/filenames/1773/original/bg-slide-box.gif'}
      %tr
        %td{:style => 'padding: 0; verticel-align:center; text-align:center; width: 474px; height: 316px; text-align: center; vertical-align: center'}
          = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1772/original/img-22.jpg"), '#'
        %td{:style => 'padding: 10px 0 0 10px; font-size: 13.5px;'}
          %div
            %span{:style => "font-size:50px; font-family: 'Pinyon Script', Julee"}
              Dear
            %span
              楊先生,
          %div{:style => 'padding:20px 10px 20px 80px; line-height:1.6'}
            在這個特別的日子
            %br
            我願以這張生日卡
            %br
            獻上最真誠的祝福
            %br
            也期望您的每一天
            %br
            都能平安 順心 美滿
            %br
            真心祝福您
            %br
            生日快樂!
          %div{:style => "text-align:right; margin-left:80px; font-family:Convergence"}
            大紀元時報 業務 Sam 敬上

  %hr{:style => 'margin: 30px 0; background: #ccc; color: #ccc'}
  %table{:style => 'font-weight: bold; font-family: Andika; vertical-align: center; color: #1967B1; width: 820px; margin: 0 auto; font-size: 14px; padding-right: 10px; padding: 15px'}
    %tr
      %td{:style => 'width: 240px; vertical-align: center; text-align: right'}
        此張卡片寄送服務 by
      %td{:style => 'width: 140px;'}
        = link_to image_tag('http://cactis.airfont.com/assets/images/filenames/1776/original/sub-logo.gif'), '#'
      %td{:style => 'vertical-align: bottom'}
        = link_to image_tag('http://cactis.airfont.com/assets/images/filenames/1777/original/btn-blue.gif'), '#'
  %div{:style => 'text-align: center'}
    %img{:src => 'http://cactis.airfont.com/assets/images/filenames/1778/original/img-ad-03.jpg'}

app/views/welcome/edm2.html (beauty's conflicted copy 2012-10-16).haml
%table{:width => '100%', :border => "0", :cellpadding => "0", :cellspacing => "0"}
  %tr
    %td{:align => 'center'}
      %hr{:style => 'margin: 50px 0; width: 820px'}
      %table{:width => '820', :style => 'font-size: 13.5px'}
        %tr
          %td{:style => 'font-size: 50px; padding-left: 20px'}
            A chirpy birthday
          %td{:style => 'text-align: right; vertical-align: bottom; padding-right: 15px'}
            = link_to "看更多生日卡", "#"
            　
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1774/original/ico-facebook-small.gif") + " 與好友分享喜悅", '#'

      %table{:width => '820', :height => '350', :border => "0", :cellpadding => "0", :cellspacing => "0", :style => 'margin: 0 auto; font-size: 13.5px'}
        %tr
          %td{:colspan => 4}
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1780/original/bg-slide-box_top.png"
        %tr
          %td
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1783/original/bg-slide-box_left.png"
          %td{:width => '500'}
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1779/original/img-22_with_player.png"), '#'
          %td{:width => 340}
            %table
              %tr
                %td{:colspan => 2}
                  = image_tag "http://cactis.airfont.com/assets/images/filenames/1786/original/dear.png", :style => 'martin-top: 10px'
                  楊先生,
              %tr
                %td{:rowspan => 2, :width => 80}
                %td{:height => 200}
                  在這個特別的日子
                  %br
                  我願以這張生日卡
                  %br
                  獻上最真誠的祝福
                  %br
                  也期望您的每一天
                  %br
                  都能平安 順心 美滿
                  %br
                  真心祝福您
                  %br
                  生日快樂!
              %tr
                %td
                  大紀元時報 業務 Sam 敬上
          %td
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1784/original/bg-slide-box_right.png"
        %tr
          %td{:colspan => 4}
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1781/original/bg-slide-box_bottom.png"

      %hr{:style => 'margin: 50px 0; width: 820px'}

      %table{:width => '820', :style => 'margin: 0 auto; text-align: center'}
        %tr
          %td{:style => 'color: #1967B1; text-align: right; font-weight: bold; padding-left: 50px'}
            此張卡片寄送服務 by
          %td{:style => 'padding-bottom: 10px'}
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1776/original/sub-logo.gif")
          %td
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1785/original/btn-blue_with_text.png")
        %tr
          %td{:colspan => 3}
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1778/original/img-ad-03.jpg")

app/views/welcome/edm2.html.haml
%table{:width => '100%', :border => "0", :cellpadding => "0", :cellspacing => "0"}
  %tr
    %td{:align => 'center'}
      %hr{:style => 'margin: 50px 0; width: 820px'}
      %table{:width => '820', :style => 'font-size: 13.5px'}
        %tr
          %td{:style => 'font-size: 50px; padding-left: 20px'}
            A chirpy birthday
          %td{:style => 'text-align: right; vertical-align: bottom; padding-right: 15px'}
            = link_to "看更多生日卡", "#"
            　
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1774/original/ico-facebook-small.gif") + " 與好友分享喜悅", '#'

      %table{:width => '820', :height => '350', :border => "0", :cellpadding => "0", :cellspacing => "0", :style => 'margin: 0 auto; font-size: 13.5px'}
        %tr
          %td{:colspan => 4}
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1780/original/bg-slide-box_top.png"
        %tr
          %td
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1783/original/bg-slide-box_left.png"
          %td{:width => '500'}
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1779/original/img-22_with_player.png"), '#'
          %td{:width => 340}
            %table
              %tr
                %td{:colspan => 2}
                  = image_tag "http://cactis.airfont.com/assets/images/filenames/1786/original/dear.png", :style => 'martin-top: 10px'
                  楊先生,
              %tr
                %td{:rowspan => 2, :width => 80}
                %td{:height => 200}
                  在這個特別的日子
                  %br
                  我願以這張生日卡
                  %br
                  獻上最真誠的祝福
                  %br
                  也期望您的每一天
                  %br
                  都能平安 順心 美滿
                  %br
                  真心祝福您
                  %br
                  生日快樂!
              %tr
                %td
                  大紀元時報 業務 Sam 敬上
          %td
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1784/original/bg-slide-box_right.png"
        %tr
          %td{:colspan => 4}
            = image_tag "http://cactis.airfont.com/assets/images/filenames/1781/original/bg-slide-box_bottom.png"

      %hr{:style => 'margin: 50px 0; width: 820px'}

      %table{:width => '820', :style => 'margin: 0 auto; text-align: center'}
        %tr
          %td{:style => 'color: #1967B1; text-align: right; font-weight: bold; padding-left: 50px'}
            此張卡片寄送服務 by
          %td{:style => 'padding-bottom: 10px'}
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1776/original/sub-logo.gif")
          %td
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1785/original/btn-blue_with_text.png")
        %tr
          %td{:colspan => 3}
            = link_to image_tag("http://cactis.airfont.com/assets/images/filenames/1778/original/img-ad-03.jpg")

app/views/welcome/index.html.haml
#backup
  %h1 資料備份
  %ul
    %li= link_to "桌面設定(XML)", archive_path(:id => "tags", :format => :xml), :target => '_blank'
    %li= link_to "桌面設定(JSON)", archive_path(:id => "tags", :format => :json), :target => '_blank'
    %li= link_to "便條紙(XML)", archive_path(:id => "notes", :format => :xml), :target => '_blank'
    %li= link_to "便條紙(JSON)", archive_path(:id => "notes", :format => :json), :target => '_blank'

app/views/welcome/index.mobile.haml
= APP[:name]
手機版