config/routes.rb
Notiz::Application.routes.draw do

  resources :interactions
  resources :sharings

  resources :archives

  resources :trees
  resources :posts
  resources :notes
  resources :clips

  resources :announces

  resources :uploads

  resources :comments
  resources :tests

  resources :notifications

  resources :images
  resources :wallpapers
  resources :attaches
  match ':controller(/:action)/:size/:id.:format' => 'images#show'
  match ':controller(/:action)/:size/:id.:format' => 'wallpapers#show'
  match ':controller(/:action)/:size/:id.:format' => 'clips#show'
  match ':controller(/:action)/:id.format' => 'attach#show'

  resources :tags do
    resources :posts
    resources :notes do
      resources :versions
    end
    resources :clips do
    end
  end

  resources :posts do
    resources :comments
  end

  resources :notes do
    resources :comments
  end

  resources :clips do
    resources :comments
  end

  resources :notes do
    resources :versions
    member do
      get 'status'
    end
  end
  get "notes/status"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :accounts
  resources :users, :controller => :accounts

  get "welcome/index"
  get 'welcome/edm'
  get 'welcome/edm2'

  root :to => 'welcome#index'

end

app/models/tag.rb
# encoding: utf-8
class Tag < Tree

  serialize :options
  custom_options = [
    ['notes_list', 'String', '99999'],
    ['float', 'Boolean', true],
    ['background', 'String', '/assets/bg/bg39.jpg'],
    ['background_color', 'String', '#ff0000'],
    ['sharing_info', 'String', 'Hi, 我有一個桌面要分享給你~'],
    ['sharing_mail_lists', 'String', '']
  ]
  acts_as_custom_options custom_options

  def posts_order_by_float(opts = {})
    # 分頁載入
    page = opts[:page] ? opts[:page].to_i : 1
    list = notes_list
    posts.order("field (posts.id, #{list.present? ? list : '00000000'})").page(page).per(30)
  end

  def name
    # 個人對標籤的自訂名稱優先於原分享者的命名
    return unless User.current
    if self.owned?
      self[:name].present? ? self[:name] : "(我的桌面)"
    else
      (User.current.tagnames && User.current.tagnames[self.id.to_s].present?) ? User.current.tagnames[self.id.to_s] : (self[:name].present? ? self[:name] : "(我的桌面)")
    end
  end

  def name=value
    if user_id.nil? || self.owned?
      self[:name] = value
    else
      user = User.current
      user.tagnames = {self.id.to_s => value}
      user.save_without_timestamping
    end
  end

  def notes_list
    if options && options[:notes_list]
      float ? options[:notes_list] : options[:notes_list].split(',').reverse.join(',')
    else
       (posts.present? ? posts.map{|note| note.id}.join(',') : '999999999')
    end
  end

  def mode
    float ? 'float' : 'absolute'
  end
end

app/controllers/tags_controller.rb
# encoding: utf-8

class TagsController < ApplicationController
  respond_to :js, :html

  def index
    render :json => Tag.select("id, name")
  end

  def new
    @tag = Tag.new
    render :layout => false
  end

  def edit
    @tag = Tag.find(params[:id])
    render :layout => false
  end

  def show
    redirect_to tag_notes_path(Tag.find(params[:id]))
    # @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.create(params[:tag])
    if @tag.save
      flash[:notice] = '已新增桌面。'
      # redirect_to tag_notes_path(@tag), :notice => flash[:notice]
      render :js => "window.location = '/tags/#{@tag.id}/notes'"
    else
    end
  end

  def update
    debug params[:tag]
    @tag = Tag.find(params[:id])
    flash[:notice] = "桌面更新完成。" if @tag.update_attributes(params[:tag])
    respond_to do |format|
      format.json { render :json => @tag.to_json }
      format.js{ render :nil => true}
      format.html {redirect_to tag_notes_path @tag}
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    if Tag.all.count > 1
      if @tag.destroy
        flash[:notice] = "己刪除。"
        # redirect_to root_url, :notice => flash[:notice]
        redirect_to tag_notes_path(Tag.first), :notice => flash[:notice]
      end
    else
      flash[:notice] = '無法刪除最後一個桌面。'
      redirect_to @tag, :notice => flash[:notice]
    end
  end
end

app/views/tags/_form.html.haml
= semantic_form_for @tag do |f|
  = f.inputs :name, :input_html => {:required => 'required'}
  .footer
    = f.buttons

app/views/tags/_tag.html.haml
.tag{:id => dom_id(tag), :class => dom_id(tag)}
  -# if (controller_name == 'tags' && params[:id].to_i == tag.id) || params[:tag_id].to_i == tag.id
    = link_to '#', '#', :class => 'config'
    .toolbar
      .switch_float
        = link_to '自動排版模式', '#', :class => tag.float ? 'true' : '', :id => 'float_1'
        = link_to '畫板模式', '#', :class => tag.float ? '' : 'true', :id => 'float_0'
      %hr
      = link_to '修改桌面名稱', '#', :class => 'naming'
      - if !tag.owned? && tag.name != tag[:name]
        = link_to "恢復原桌面名稱!(#{tag[:name]})", '#', :class => 'undo_naming'

      = link_to '恢復原始桌布!', '#', :class => 'restore_wallpaper' if tag.owned?
      - if tag.owned?
        %hr
        = link_to '分享給...', new_sharing_path(:tag_id => tag.id), :class => 'share colorbox'
        %hr
        = link_to '刪除桌面', @tag, :confirm => "刪除 '#{tag.name}'，並一併將桌面所含便條紙刪除？", :class => 'delete1', :method => :delete if Tag.all.count > 1
  = link_to tag.name, tag_notes_path(tag), :class => 'goto'

-# if (controller_name == 'tags' && params[:id].to_i == tag.id) || (@tag && params[:tag_id].to_i == tag.id)
  .floatRight
    = link_to '*', edit_tag_path(tag), :remote => true, :class => 'colorbox edit'
    = link_to '-', @tag, :confirm => "刪除 '#{@tag.name}'，並一併將桌面所含便條紙刪除？", :class => 'delete', :method => :delete if Tag.all.count > 1

app/views/tags/_tag.mobile.haml
.tag{:id => dom_id(tag), :class => dom_id(tag)}
  -# if (controller_name == 'tags' && params[:id].to_i == tag.id) || params[:tag_id].to_i == tag.id
    = link_to '#', '#', :class => 'config'
    .toolbar
      .switch_float
        = link_to '自動排版模式', '#', :class => tag.float ? 'true' : '', :id => 'float_1'
        = link_to '畫板模式', '#', :class => tag.float ? '' : 'true', :id => 'float_0'
      %hr
      = link_to '修改桌面名稱', '#', :class => 'naming'
      - if !tag.owned? && tag.name != tag[:name]
        = link_to "恢復原桌面名稱!(#{tag[:name]})", '#', :class => 'undo_naming'

      = link_to '恢復原始桌布!', '#', :class => 'restore_wallpaper' if tag.owned?
      - if tag.owned?
        %hr
        = link_to '分享給...', new_sharing_path(:tag_id => tag.id), :class => 'share colorbox'
        %hr
        = link_to '刪除桌面', @tag, :confirm => "刪除 '#{tag.name}'，並一併將桌面所含便條紙刪除？", :class => 'delete1', :method => :delete if Tag.all.count > 1
  = link_to tag.name, tag_notes_path(tag), :class => 'goto'

-# if (controller_name == 'tags' && params[:id].to_i == tag.id) || (@tag && params[:tag_id].to_i == tag.id)
  .floatRight
    = link_to '*', edit_tag_path(tag), :remote => true, :class => 'colorbox edit'
    = link_to '-', @tag, :confirm => "刪除 '#{@tag.name}'，並一併將桌面所含便條紙刪除？", :class => 'delete', :method => :delete if Tag.all.count > 1

app/views/tags/_tags.html.haml
.tags
  = render :partial => '/tags/tag', :collection => Tag.order("field (trees.id, #{current_user.tags_list})")
  = link_to '+', '#', :id => 'add_tag', :title => '新增桌面', :class => 'add1 icon icons_add_tag'

:coffeescript
  $(document).ready ->
    $('#add_tag').click ->
      if name = prompt('請輸入桌面名稱：', '我的桌面')
        $.ajax
          url: '/tags'
          type: 'POST'
          data:
            tag:
              name: name
      false


    if Notiz.tags.current.id
      $(".tag_" + Notiz.tags.current.id).addClass('active')

    $('.tags')
      .sortable
        items: 'div'
        delay: 500
        axis: 'x'
        cursor: 'move'
        #'crosshair'
        start: (e, ui) ->
        stop: (e, ui) ->
          list = []
          $(this).find('.tag').each ->
            list.push $(this).attr('id').split('_')[1]
          $.ajax
            url: '/accounts/#{current_user.id}'
            type: 'put'
            data:
              account:
                tags_list: list.join(',')

app/views/tags/_tags.mobile.haml
.tags
  = select_tag :tag, options_for_select(Tag.order("field (trees.id, #{current_user.tags_list})").map{|t| [t.name, t.id]}, params[:tag_id]), :include_blank => true


:coffeescript
  $('document').ready ->
    $('#tag').change (e) ->
      window.location.href = '/tags/' + e.target.value
      -# $.ajax
        url: '/tags/' + e.target.value + '/notes'
        success: (data, textStatus, jqXHR) ->
          $('#content').html(data)
          $.fn.log data
          $.fn.log textStatus
          $.fn.log jqXHR
      $.fn.log e
      $.fn.log e.target.value
      $.fn.log e.target.selectedIndex
      $.fn.log $('option[value=' + e.target.value + ']').html()

app/views/tags/edit.html.haml
= javascript_include_tag 'tags_edit'

#tag_config_form.option
  .content
    .title 桌面設定
    = form_for @tag, :remote => true do |f|
      .row
        = f.label :name, "桌面名稱"
        = f.text_field :name, :required => 'required', 'data-old' => @tag.name, :value => @tag.name
        - if !@tag.owned? && @tag.name != @tag[:name]
          .footer
            = link_to "恢復原桌面名稱! (#{@tag[:name]})", '#', :class => 'undo_naming button'
      .row
        顯示模式
        = f.radio_button :float, true
        = f.label :float, "自動排版"
        = f.radio_button :float, false
        = f.label :float, "畫板模式"

      - if @tag.owned?
        %hr
        邀請:
        .row
          = f.label :sharing_info, "邀請用語"
          = f.text_field :sharing_info, 'data-old' => @tag.sharing_info
        .row
          = f.label :label, "邀請對象"
          = f.text_field :sharing_mail_lists, 'data-old' => @tag.sharing_mail_lists, :title => '以 ; 號分隔多組帳號'
        .row
          同時邀請多人時，請用逗號或分號間隔。
          = link_to '發送邀請函', '#', :class => 'button', :id => 'send_sharing_mail'
        %hr
        拖拉電腦檔案夾裡的任何圖片至桌面左下角的「更換桌面」圖示上，即可立即更換桌布。
        = link_to '恢復原始桌布!', '#', :class => 'restore_wallpaper button'
        %hr
        移除本桌面時，相關物件，如便條紙、圖卡及附件會一併刪除。
        = link_to '移除桌面!!', @tag, :confirm => "移除本 '#{@tag.name}' 桌面，並一併將桌面上的所有物品送入碎紙機？", :class => 'button', :method => :delete if Tag.all.count > 1
        %hr
        關於:<br/>
        = about @tag
    = link_to '#', '#', :class => 'close_30 icon icons_close'

app/views/tags/new.html.haml
%h1 New Tag

= render 'form'

app/views/tags/show.html.haml
#notes.notes{:class => @tag.mode}
  = render @notes